### ISSUE TITLE
How long does it take to generate 1.blenger?

### ISSUE THREAD

**Issue by yxt7979** [xinyazhang/PuzzleTunnelDiscovery#2]
After I run all the sample code, i still can not have 1.blender in u3/duet-g2. Does it take a long time? Or there is something wrong qaq?
![image](https://user-images.githubusercontent.com/62125435/137140238-63f0366a-c2b8-40f8-945e-70c7d7a85de7.png)

**Comment by yxt7979** [comment]
How can I get 1.blender ?qwq

**Comment by yxt7979** [comment]
or can you send me your 1.blender to my email : 3225155810@qq.com  ?

**Comment by xinyazhang** [comment]
`./facade.py tools blender` should always exit immediately (even if it failed).

A few things to check
1. Did you see a green line output like `Saving UNIT solution of duet-g2 to /home/puz/PuzzleTunnelDiscovery/bin/u3/duet-g2/test/duet-g2/path-3.nt-unit.txt`?
2. It seems I forgot to package scipy into the bundled blender 2.83. Make sure you run the following command in the container before trying to generate the file
```
sudo /app/blender-2.83.4-linux64/2.83/python/bin/python3.7m -m ensurepip
sudo /app/blender-2.83.4-linux64/2.83/python/bin/python3.7m -m pip install scipy
```
3. If you really need the file, here it is:
[3.blender.gz](https://github.com/xinyazhang/PuzzleTunnelDiscovery/files/7340108/3.blender.gz)
4. I think the problem is about running everything with sudo, don't do that, otherwise the owner of files will be root and there would be permission issues.

P.S. The `create-workspaces.sh` in the container image was bugged, which always put aj puzzle into the workspace.
A fix is coming

**Comment by yxt7979** [comment]
Okeyyy! Thanks a lot!
